spring:
  application:
    name: web-app
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  datasource: #本地模式
#    chaos:
#      url: jdbc:mysql://localhost:3306/test
#      username: root
#      password: root
#      hikari:
#        maximum-pool-size: 10
#        connection-timeout: 3000
# Web 服务配置
server:
  port: ${WEB_SERVER_PORT:8081}
  servlet:
    context-path: /

# gRPC 客户端配置
grpc:
  server:
    enabled: false  # 显式禁用 gRPC 服务端
    port: -1        # 设置端口为 -1 进一步确保不启动
  client:
    # UserService 客户端配置
    user-service:
      address: static://localhost:9091
      negotiationType: plaintext
    # OrderService 客户端配置
    order-service:
      address: static://localhost:9092
      negotiationType: plaintext

    chaos-service: #rpc 模式
      address: static://localhost:9090
      negotiationType: plaintext

# 日志配置
logging:
  level:
    com.ddm.demo: DEBUG
    com.ddm.argus: INFO
    net.devh.boot.grpc: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{lane:--}] [%X{traceId:--}] %logger{36} - %msg%n"

chaos:
  config-center:
    profiles: [ "gray", "hotfix" ]
    ttl: 30S
---

spring:
  config:
    activate:
      on-profile: test

grpc:
  client:
    user-service:
      address: "cloud:///demo-user-rpc.test.local"
    order-service:
      address: "cloud:///demo-order-rpc.test.local"

